---
- hosts: localhost
  vars:
    docker_compose:
      version: 2.4.1
    goenv:
      versions:
        - 1.18.0
        - 1.17.8
    pyenv:
      versions:
        - 3.10.4
        - 3.9.12
        - 2.7.18
  roles:
    - docker 
      #- docker-compose
      #- goenv
      #- pyenv
